Si una llamada nos da un error podemos encontrar el resultado en
$!


open LIMITS, "nom"
