https://gobyexample.com/panic

Es una especie de excepción.
Termina el programa con una traza de donde se salió y un mensaje custom.
Al contrario que las excepciones, no parece que existe algo parecido a un try-catch

panic("mensaje")
